# TEST CONFIG

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5