module:
  imports: 
    # Add the Netlify CMS module below, if it has not already been added:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
