############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
  - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
  - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
